# .github/workflows/ci.yml
name: Chatbot CI

on:                         # run on every push or PR to main
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest  # fresh Linux VM
    strategy:
      matrix:
        python-version: [ "3.10" ]  # adjust if you need other versions
    steps:
      - uses: actions/checkout@v4   # pulls your code
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
